### ISSUE TITLE
Unknown shorthand flag f in -d

### ISSUE THREAD

**Issue by danieltomasz** [josephmachado/analytical_dp_with_sql#10]
When trying to run first command `make up` I receiving this output
```
make up
docker volume rm --force minio-data
minio-data
docker compose up -d --build
unknown shorthand flag: 'd' in -d
See 'docker --help'.
```

MacOS 13.4 M1, 
Docker version 24.0.2, build cb74dfcd85

I am using colima for containers runtimes

**Comment by josephmachado** [comment]
Hi @danieltomasz Thank you for opening the issue. May I ask what your docker compose version is?

From the error, it looks like the command `docker compose up -d --build` is not working. Which indicates that the docker compose may be at fault here.

You will need to have [docker compose v2](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command) for this command to run, you can check the compose version as follows

```bash
➜  analytical_dp_with_sql git:(main) docker compose version
Docker Compose version v2.10.2
```
Please lmk what your version of docker compose is.

**Comment by danieltomasz** [comment]
```
docker-compose --version
Docker Compose version 2.18.1
```
but 
```
docker compose --version
Docker version 24.0.2, build cb74dfcd85
```

The fix was to use `docker-compose` instead of `docker compose`
but then the error 
```
 make up
docker volume rm --force minio-data
minio-data
docker-compose up -d --build
[+] Running 5/5
 ✘ hive-metastore Error                                                   30.0s
 ✘ trino-coordinator Error                                                20.1s
 ✘ mariadb Error                                                          20.1s
 ✘ createbuckets Error                                                    20.1s
 ✘ minio Error                                                            20.1s
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.107.1:53: read udp 192.168.107.2:54945->192.168.107.1:53: i/o timeout
make: *** [up] Error 18
```

**Comment by josephmachado** [comment]
Please use Docker Compose version v2 as mentioned in the [README](https://github.com/josephmachado/analytical_dp_with_sql). [Docker compose v1 will not receive updates.](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command)

You are using the older version of docker compose.

As for the connection issue, can you 
1. Try restarting docker
2. Allowing this connection if you are using a firewall

**Comment by danieltomasz** [comment]
Yes, regarding the latest error, it was network problems on my side (university vpn  I was on), I figured after posting but I didnt have time to reply; Everything works now! :) 

Regarding `docker compose` from command line that I posted earlier I am using 2.18.1>2.10 which was released last month). Brew also list this version as its formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-compose.rb

 `docker compose` is meant to be linux only tool as it specified in the documentation [here](https://docs.docker.com/compose/install/#:~:text=This%20is%20only%20available%20on%20Linux),  syntax  issue regarding `docker compose` vs `docker-compose` might be some peculiarity of installing it as a plugin on macos

I might close this issue, but maybe other macos users can confirm if they can use `docker compose` vs `docker-compose`

**Comment by danieltomasz** [comment]
Ok I did quick search, `Docker Desktop on Mac` is shipping with `docker compose` and thus command `docker compose` is valid

`brew install docker docker-compose` install only command-line tools (latest version), but `docker compose` need to be accessed via `docker-compose` as a  plugin
(later edit)
to use `docker compose' , 'docker-compose' need to be symlinked after installing via `homebrew`
```
Compose is now a Docker plugin. For Docker to find this plugin, symlink it:
  mkdir -p ~/.docker/cli-plugins
  ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
```
