### ISSUE TITLE
[MariaDB] Hive metastore not working with some versions of MariaDB 

### ISSUE THREAD

**Issue by caldowa** [josephmachado/analytical_dp_with_sql#11]
**Describe the bug**
When using latest version of the MariaDB docker image, the hive-metastore container keep shutting down because of the following error : `java.sql.SQLException : Unknown system variable 'transaction_isolation'`

**To Reproduce**
1. Run `make up`

**Expected behavior**
All the required containers must spin up.

**Screenshots**
<img width="1186" alt="image" src="https://github.com/josephmachado/analytical_dp_with_sql/assets/103035259/b8e53e62-9820-4f10-9712-553f1848807a">

**Desktop (please complete the following information):**
 - OS: MacBook Pro Intel, MacOS Ventura

**Additional context**
I've found this [thread](https://jira.mariadb.org/browse/MDEV-23520?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true) that mentions the error. They suggest that the error doesn't happen with version `10.3.32` of mariadb.
I've tried restricting the image to that version and haven't encountered any issues yet.

It also seems to be an [open issue](https://github.com/sysown/proxysql/issues/3017) on MariaDB's repo.

I thought I'd let you know @josephmachado 😊

**Comment by josephmachado** [comment]
Thank you so much for reporting this @caldowa 
I should have pinned versions and not use latest. I made the changes in [this PR](https://github.com/josephmachado/analytical_dp_with_sql/pull/12)

**Comment by caldowa** [comment]
Thank you for the quick response @josephmachado ! I'm glad that's settled, it'll allow me to keep going through your book 😄 I'm really enjoying it.

**Comment by josephmachado** [comment]
Sure thing. Really glad that you are enjoying the book! :)

Please feel free to reach out if you have any questions or concerns.
