### ISSUE TITLE
Unable to connect to Docker

### ISSUE THREAD

**Issue by lr67892r** [josephmachado/analytical_dp_with_sql#13]
Hi, I am a little stuck and not sure how to resolve this issue of not being able to connect to Docker. Appreciate your help thank you!!

![Screenshot 2023-09-04 000653](https://github.com/josephmachado/analytical_dp_with_sql/assets/143954434/1d047781-4688-40c8-a357-bb934288717b)

**Comment by josephmachado** [comment]
Hi @lr67892r This message means docker is not running on your OS. You can install [docker desktop](https://www.docker.com/products/docker-desktop/) (if you don't have it already), opening that will start docker on your OS.

Once docker is running, please use `make up` to start these containers.

LMK if this works.

**Comment by lr67892r** [comment]
Yes thank you! All is in order now 👍
