### ISSUE TITLE
remote access project via SSH

### ISSUE THREAD

**Issue by luutuankiet** [josephmachado/analytical_dp_with_sql#6]
**Describe the bug**
I decided to use my home machine as development server for this project while sending commands via ssh from a client device. The setup went through until `make trino` that it threw the following error below (pardon my lack of pasting, I am figuring out how to access clipboards in ssh)
![image](https://user-images.githubusercontent.com/56199834/223484063-937e207f-70a9-4e8c-8f28-c4ab1835e06a.png)

Is there additional configurations to be setup with SSH ? I assume that it's missing port forwarding.

**To Reproduce**
1. make up
2. wait for 60s
3. make trino

**Expected behavior**
I can proceed to next steps with trino gui.

**Screenshots**
please see list of running containers:
![image](https://user-images.githubusercontent.com/56199834/223484761-f43f0ef7-e9c1-49d5-bd79-1216d60d5a2f.png)

**Desktop (please complete the following information):**
 - OS: linux mint 21.1

**Comment by josephmachado** [comment]
Hi @luutuankiet It looks like the `trino-coordinator` container is not running. ~~Can you please run `docker logs trino-coordinator` on the dev server and paste the results here? I am not able to replicate this issue locally.~~

**Comment by josephmachado** [comment]
hi @luutuankiet, Can you please do a `git pull` and try it again? I've [merged a fix](https://github.com/josephmachado/analytical_dp_with_sql/pull/7). Thank you for opening this issue.

If this works, please close the issue, else lmk.

**Comment by luutuankiet** [comment]
hey working as expected. Thanks for the prompt action!
