### ISSUE TITLE
Misc - alternative editor to trino cli for intuitition purpose

### ISSUE THREAD

**Issue by luutuankiet** [josephmachado/analytical_dp_with_sql#8]
**Describe the bug**
Hi, novice sql learner here - I appreciate your effort setting up the repo with seamless makefile steps to consume the book with practical code on hand. 
The problem is that coming from other native SQL editors (SSMS, VS, notepad++ etc) I find that the CLI compared to them is **much more cramped and unintuitive to edit / explore the input SQL code**.

I think being able to do the following on an editor can massively help consume the code and thus the book core concept :
- partial execution - being able to highlight part of the code and execute away to quickly inspect the input
- accessibility to source SQL code between executions : it's neat having the execution results in the same section, but at the same time it is pushing the source sql code out of the terminal view - which after some executions makes it **impractical to retrieve the earlier queries**. _(as opposed to (SSMS) a separate editor that stays put regardless of the execution result.)_
- (should have) better syntax highlighting - way it is now the base clause such as SELECT / FROM / WHERE / GROUP BY etc are in plain black and bold which can be easy to misread along with the rest of the code.

**Expected behavior**
would you suggest an alternative / some tips with the CLI to achieve the above?

**Comment by josephmachado** [comment]
TYVM @luutuankiet 

These are great points. My suggestion would be to use DBeaver as a SQL IDE. There are others from intellij, vscode SQL editors, etc, I've found DBeaver to be easiest to setup, use and manage.

I have updated the README with details on connecting to DBeaver ([PR](https://github.com/josephmachado/analytical_dp_with_sql/pull/9)) and will add these to the next book version.

Appreciate the time and effort you put in this PR. Feel free to reopen if the PR does not solve the questions.

**Comment by luutuankiet** [comment]
@josephmachado thanks for the pointers! on this approach i am looking to connect dbeaver remotely to the trinodb **from another machine via ssh** - let me know if you have done this before?

the context is that i usually ssh to my home machine hosting the repo and docker container so ideally I can spin them up on that, then use my other machines to ssh in as a lightweight portal - which worked with trino CLI approach.
